kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
provisioner: ebs.csi.eks.amazonaws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
  # The following parameters are specific to the EBS CSI driver.
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3
  encrypted: "true"
  tagSpecification_1: Name=ebs-sc
  tagSpecification_2: CostCentre=my-project