apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raghureddycloud/kcdblr-demo-001.git
    targetRevision: HEAD
    path: kubeflow
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true